<script src="js/mascaras.js"></script>

<section id="conteudo" class="d-flex">
  <div class="container align-self-center">
    <div class="row">
      <div class="col-md-5 mx-auto bg-white rounded">

        <div class="text-primary text-center mb-5 mt-4">
          <h2 class="font-weight-bold">Crie sua conta para agendar</h2>
        </div>        
          
        <form action="/cadastrar_cli2" method="post">
          <div class="form-group">
            <label class="text-dark mr-2 pt-2" for="nome">Nome</label>
            <input id="nome" required value="<?= $this->view->cliente['nome']; ?>" name="nome" type="text" class="form-control">
          </div>

          <div class="form-group">
            <label class="text-dark mr-2 pt-2" for="cpf">Cpf</label>
            <input id="cpf" required value="<?= $this->view->cliente['cpf']; ?>" name="cpf" type="text" class="form-control">
          </div>

          <div class="form-group">
            <label class="text-dark mr-2 pt-2" for="telefone">Telefone</label>
            <input id="telefone" required value="<?= $this->view->cliente['telefone']; ?>" name="telefone" type="text" class="form-control">
          </div>
          
          <div class="form-group">
            <label class="text-dark mr-2 pt-2" for="email">Email</label>
            <input id="email" required value="<?= $this->view->cliente['email']; ?>" name="email" type="text" class="form-control">
          </div>

          <div class="form-group">
            <label class="text-dark mr-2 pt-2" for="senha">Senha</label>
            <input id="senha" required value="<?= $this->view->cliente['senha']; ?>" name="senha" type="password" class="form-control">
            <small class="form-text text-dark mb-3">*A senha deve ter no mínimo 4 e no máximo 8 caracteres.</small> 
          </div>                
          
          <button type="submit" class="btn btn-primary btn-block mt-5 mb-4">Cadastrar</button>

          <?php if($this->view->erroCadastro){ ?>

            <small class="form-text text-danger mb-3">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente ou se já possui cadastro conosco.</small>  

          <? } ?>

        </form>
            
      </div>
    </div>
  </div>

</section>