<section id="conteudo" class="d-flex justify-content-center">
    
    <div class="align-self-center container">
            
        <div class="text-center">
            <h3 class="text-info font-weight-bold mb-5 mt-4">Contato | Endereço</h3>            
            <p>Plantão de domingo a domingo até as 22:00 horas</p>
            <p>Agendamentos apenas de segunda a sexta das 8:00 horas às 16:00 horas</p>
            <p><i class="fas fa-phone mr-2"></i><i class="fab fa-whatsapp mr-2"></i>Contato (11) XXXXX-XXXX</p>
            <p>Rua XXXXXXXXX NºXXXX Bragança Pta</p>
        </div>                   

    </div>
    
</section>