<section id="conteudo">
	<div class="container">
		
		<div class="titulo">
			VetPet - Clínica Veterinária
		</div>		

		<div>			

			<div class="carousel slide d-none d-md-block" data-ride="carousel">

				<div class="carousel-inner">

					<div class="carousel-item active">   
						<img class="img" src="imagens/gato_foto1.jpg"alt="">
					</div>

					<div class="carousel-item">	
						<img class="img" src="imagens/cao_foto1.jpg" alt="">
					</div>                

				</div>					

			</div>

			<div class="carousel slide d-md-none d-lg-none d-xl-none" data-ride="carousel">

				<div class="carousel-inner">

					<div class="carousel-item active"> 
						<img class="img" src="imagens/gato_foto2.jpg"alt="">
					</div>

					<div class="carousel-item">		
						<img class="img" src="imagens/cao_foto2.jpg" alt="">
					</div>                

				</div>					

			</div>
			
		</div>

	</div>

	<div class="bg-white mt-5 py-5 px-3">

		<div class="container">

			<div class="row">
				<div class="col-md-4 p-4">
					<h3 class="text-info mb-4 font-weight-bold">Excelência profissional</h3>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis turpis ultrices,
						imperdiet lectus quis, consequat sapien.
					</p>
				</div>
				<div class="col-md-4 p-4">
					<h3 class="text-info mb-4 font-weight-bold">Dedicação</h3>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis turpis ultrices,
						imperdiet lectus quis, consequat sapien.
					</p>
				</div>
				<div class="col-md-4 p-4">
					<h3 class="text-info mb-4 font-weight-bold">Amor pelos animais</h3>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis turpis ultrices,
						imperdiet lectus quis, consequat sapien.
					</p>
				</div>
			</div>

		</div>

	</div>

	<div class="mt-3 py-5 px-4 text-center">
		<h3 class="text-info mb-4 font-weight-bold">Atendimentos</h3>
		<p>Plantão de domingo a domingo até as 22:00 horas</p>
		<p>Agendamentos apenas de segunda a sexta das 8:00 horas às 16:00 horas</p>
		<p><i class="fas fa-phone mr-2"></i><i class="fab fa-whatsapp mr-2"></i>Contato (11) XXXXX-XXXX</p>
		<p>Rua XXXXXXXXX NºXXXX Bragança Pta</p>
	</div>

</section>