<section id="conteudo">

    <div class="px-3">    
    
        <div class="container mt-4">

            <div class="row">

                <div class="col-md-7 mx-auto">
                    <div class="">
                        <h3 class="text-info font-weight-bold mb-5">Nossos serviços</h3>
                        <h5 class="mb-4 font-weight-bold">CONSULTAS</h5>
                        <p class="text-justify">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                            when an unknown printer took a galley of type and scrambled it to make a type
                            specimen book. It has survived not only five centuries, but also the leap into electronic
                            typesetting, remaining essentially unchanged. It was popularised in the 1960s with the 
                            release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                            publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                </div>
            </div>        

        </div>

    </div>

    <div class="bg-white mt-4 pb-4 px-3">

		<div class="container">

			<div class="row">
				<div class="col-md-7 mx-auto">
                    <h5 class="mb-4 font-weight-bold mt-5">PLANTÃO DIÁRIO ATÉ ÀS 22:00 HORAS</h5>
					<p class="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and scrambled it to make a type
                        specimen book. It has survived not only five centuries, but also the leap into electronic
                        typesetting, remaining essentially unchanged. It was popularised in the 1960s with the 
                        release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                        publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
				</div>				
			</div>

		</div>

	</div>

    <div class="px-3"> 

        <div class="container mt-4">

            <div class="row">

                <div class="col-md-7 mx-auto">
                    <div class="">
                        <h5 class="mb-4 font-weight-bold pt-4">VACINAS</h5>
                        <p class="text-justify">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                            when an unknown printer took a galley of type and scrambled it to make a type
                            specimen book. It has survived not only five centuries, but also the leap into electronic
                            typesetting, remaining essentially unchanged. It was popularised in the 1960s with the 
                            release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                            publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </p>
                    </div>
                </div>
            </div>        

        </div>
    </div>

    <div class="bg-white mt-4 pb-4 px-3">

		<div class="container">

			<div class="row">
				<div class="col-md-7 mx-auto">
                    <h5 class="mb-4 font-weight-bold mt-5">CIRURGIAS</h5>
					<p class="text-justify">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and scrambled it to make a type
                        specimen book. It has survived not only five centuries, but also the leap into electronic
                        typesetting, remaining essentially unchanged. It was popularised in the 1960s with the 
                        release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop
                        publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                    </p>
				</div>				
			</div>

		</div>

	</div>
</section>