<section id="conteudo" class="d-flex">
  <div class="container align-self-center">
    <div class="row">
      <div class="col-md-5 mx-auto bg-white rounded">

        <div class="d-flex justify-content-center">
          <i class="fas fa-cat fa-2x mt-4"></i>
        </div>          

        <div class="text-info text-center mb-4 mt-4">
          <h2 class="font-weight-bold"><?= $this->view->mensagem_sucesso ?></h2>
        </div>   
        
        <div class="d-flex justify-content-center">
          <a href="<?= $this->view->link_menu ?>" class="btn btn-info mb-4 btn-lg btn-block">Voltar ao menu</a>
        </div>    
            
      </div>
    </div>
  </div>
</section>