<!DOCTYPE html>
<html lang="pt-br">
  <head>
	
    <title>VetPet - Clínica veterinária</title>
      
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    

    <script src="https://kit.fontawesome.com/13cc78eee6.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="css/estilo.css">    

  </head>

  <body>

    <header class="cabecalho">
          <nav class="navbar navbar-expand-xl navbar-light">
    
            <div class="container">
    
              <a id="logo" href="/" class="navbar-brand">VetPet</a>         
    
              <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
                <i class="fas fa-bars text-white"></i>
              </button>
    
              <div id="nav-principal" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">                               
                  <li class="nav-item">
                    <a href="/" class="nav-link">Home</a>
                  </li>
                  <li class="nav-item">
                    <a href="/quem_somos" class="nav-link">Quem somos</a>
                  </li>                                                  
                  <li class="nav-item">
                    <a href="/servicos" class="nav-link">Serviços</a>
                  </li>
                  <li class="nav-item">
                    <a href="/contato_endereco" class="nav-link">Contato/Endereço</a>
                  </li>
                  <li class="nav-item divisor"></li>
                  <li class="nav-item">
                    <a href="/cadastrar_cli" class="nav-link">Cadastre-se</a>
                  </li> 
                  <li class="nav-item divisor"></li>
                  <li class="nav-item">
                    <a href="/login_cli" class="nav-link">Agendamentos<i class="fas fa-heartbeat fa-lg ml-2"></i></a>
                  </li>                
                </ul>
                
              </div>
              
            </div>
            
          </nav>
      </header>

    <?= $this->content() ?>

    <footer class="text-center">
      <div>
        <p>&copy; Copyright 2022.</p>
        <p class="mb-3">Produzido por Leonardo Gomes</p>
      </div>
    </footer>

  </body>

</html>